version: "3"

services:
  master:
    build: salt-master
    privileged: true
    hostname: master
    container_name: master
  minion:
    build: salt-minion
    privileged: true
    hostname: minion
    container_name: minion
    links:
      - master
  nefario:
    build: .
    container_name: api
    links:
      - master
  redis:
    image: "redis:alpine"
    container_name: redis
